config/routes.rb
Rails.application.routes.draw do
  root 'groups#index'
  devise_for :users
  resources :users, only: [:edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.name?
        last_message.name
      else
        'データが投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.

  validates :name, presence: true # Make sure the owner's name is present.

  has_many :okays, dependent: :destroy
  has_many :okays_messages, through: :okays, source: :message
end

app/models/okay.rb
class Okay < ApplicationRecord
  belongs_to :message
  belongs_to :user
  validates_uniqueness_of :message_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
  
  validates :name, presence: true, uniqueness: true
  has_many :okays, dependent: :destroy
  has_many :okays_users, through: :okays, source: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  def index
  end
  
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @messages = Message.all.uniq
    @messages = @group.messages.includes(:user)
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params.require(:message).permit(:name, :attachment))
    @message.save
    @message = @group.messages.new(message_params)
      if @message.save
        redirect_to group_messages_path#, notice: "The message #{@message.name} has been uploaded."
      else
        render "new"
      end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to group_messages_path
  end

private
  def message_params
    params.require(:message).permit(:name, :attachment).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/okeys_controller.rb
class OkeysController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/okeys_helper.rb
module OkeysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "保存", class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'messages/left_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title JobContact
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/_create_bar.html.haml
.create_bar
  = form_for [@group, @message], :html => {multipart: true, :class => "form-horizontal image" }  do |f|
    .form-message
      = f.label :メッセージ, class: 'form-message__item'
      = f.text_field :name, class: 'form-message__content'
    %br/
    .form-data
      = f.label :DATA
      = f.file_field :attachment
      = f.submit "送信", class: "btn-primary"
    .home-btm
      = link_to group_messages_path do
        = icon('fas', 'home fa-2x' )

app/views/messages/_left_bar.html.haml
.left-bar
  .left-header
    .left-header__box
      %p.left-header__box__name
        = current_user.name
      %ul.left-header__box__menu
        %li.left-header__box__menu__edit
          = link_to new_group_path do
            グループ作成

  .groups
    - current_user.groups.each do |group|
      .group
        = link_to group_messages_path(group) do
          .group__name
            = group.name
          .group__message
            = group.show_last_message

app/views/messages/_main_bar.html.haml
.chat-main
  .main-header
    .main-header__group
      %h1.main-header__group__name
        = @group.name

    = link_to edit_group_url(@group) do
      .main-header__edit-btn
        編集
  
  .messages
    .message
      %table
        %tr
          %th メッセージ
          %th 投稿データ
          %th  
        - @messages.each do |message|
          %tr
            %td= message.name
            %td= link_to message.attachment.to_s.gsub('/', ' ').split.last, message.attachment_url
            %td= button_to "削除", group_message_path([@group], id: message) , method: :delete, class: "btn-red"

app/views/messages/_right_bar.html.haml
.right-bar
  .logout
    .logout-btn
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'

  .others
    .other
      %ul.other__list
        %li.other__list__name
          - @group.users.each do |user|
            %li= user.name

  .posts
    .post
      = link_to "アップロード", new_group_message_path, class: "btn-primary"

app/views/messages/index.html.haml
.wrapper
  = render "left_bar"
  = render "main_bar"
  = render "right_bar"

app/views/messages/new.html.haml
.wrapper
  = render "create_bar"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 アカウントの編集
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .actions
          = f.submit "アップデート", class: 'btn'